name: Reachability Report
on:
  workflow_dispatch:

jobs:
  generate-deep-sitemap:
    name: "Generate Deep Sitemap"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install crawler deps
        run: |
          npm install puppeteer sitemapper ts-node
      - name: Generate sitemap
        uses: actions/upload-artifact@v4
        run: |
          sitemap=$(ts-node .github/workflows/scripts/generateDeepSitemap.ts)
        with:
          name: portal-deep-sitemap
          path: |
            $sitemap
  generate-reachability-report:
    name: "Generate reachability report"
    runs-on: ubuntu-latest
    steps:
      - name: Download sitemap
        uses: actions/download-artifact@v4
        with:
          name: portal-deep-sitemap
      - name: Reach all links in sitemap
        run: |
          cat "$GITHUB_WORKSPACE/portal-deep-sitemap"